// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using language_proficiency_blockchain.Database;

#nullable disable

namespace language_proficiency_blockchain.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111213917_RemoveUserRoleProperty")]
    partial class RemoveUserRoleProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.BlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PrevHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("PrevId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("SignedHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("PrevId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b6749-15c6-7d7d-b276-cea3b005f79f"),
                            Hash = new byte[] { 212, 66, 182, 77, 86, 235, 67, 91, 113, 74, 58, 132, 205, 131, 118, 95, 130, 154, 225, 220, 52, 170, 117, 29, 80, 22, 92, 198, 205, 247, 142, 2 },
                            PrevHash = new byte[0],
                            PrevId = new Guid("019b6749-15c6-7d7d-b276-cea3b005f79f"),
                            SignedHash = new byte[0],
                            Timestamp = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "FirstBlock"
                        });
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.InstitutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PublicKeyPem")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("BlockId")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Surname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaxScore")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId")
                        .IsUnique();

                    b.HasIndex("InstitutionId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("TestId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.UserRoleAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.BlockEntity", b =>
                {
                    b.HasOne("language_proficiency_blockchain.Database.Models.InstitutionEntity", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId");

                    b.HasOne("language_proficiency_blockchain.Database.Models.BlockEntity", "PrevBlock")
                        .WithMany()
                        .HasForeignKey("PrevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("PrevBlock");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.InstitutionEntity", b =>
                {
                    b.HasOne("language_proficiency_blockchain.Database.Models.BlockEntity", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.TestEntity", b =>
                {
                    b.HasOne("language_proficiency_blockchain.Database.Models.BlockEntity", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("language_proficiency_blockchain.Database.Models.InstitutionEntity", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.TestResultEntity", b =>
                {
                    b.HasOne("language_proficiency_blockchain.Database.Models.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("language_proficiency_blockchain.Database.Models.TestEntity", "TestEntity")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TestEntity");
                });

            modelBuilder.Entity("language_proficiency_blockchain.Database.Models.UserRoleAssociation", b =>
                {
                    b.HasOne("language_proficiency_blockchain.Database.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
